var annotated_dup =
[
    [ "Bomber", "class_bomber.html", "class_bomber" ],
    [ "Building", "class_building.html", "class_building" ],
    [ "Button", "class_button.html", "class_button" ],
    [ "Command", "struct_command.html", "struct_command" ],
    [ "CommandQueue", "class_command_queue.html", "class_command_queue" ],
    [ "DragonButton", "class_dragon_button.html", "class_dragon_button" ],
    [ "endOfFile", "classend_of_file.html", "classend_of_file" ],
    [ "EndTurnButton", "class_end_turn_button.html", "class_end_turn_button" ],
    [ "Factory", "class_factory.html", "class_factory" ],
    [ "Game", "class_game.html", "class_game" ],
    [ "GameObject", "class_game_object.html", "class_game_object" ],
    [ "Headquarters", "class_headquarters.html", "class_headquarters" ],
    [ "HolyGrail", "class_holy_grail.html", "class_holy_grail" ],
    [ "InputHandler", "class_input_handler.html", "class_input_handler" ],
    [ "MenuButton", "class_menu_button.html", "class_menu_button" ],
    [ "Music", "class_music.html", "class_music" ],
    [ "Player", "class_player.html", "class_player" ],
    [ "PlayerButton", "class_player_button.html", "class_player_button" ],
    [ "PlayerObject", "class_player_object.html", "class_player_object" ],
    [ "ReadText", "class_read_text.html", "class_read_text" ],
    [ "Recruit", "class_recruit.html", "class_recruit" ],
    [ "RecruitButton", "class_recruit_button.html", "class_recruit_button" ],
    [ "Resource", "class_resource.html", "class_resource" ],
    [ "ResourceHolder", "class_resource_holder.html", "class_resource_holder" ],
    [ "Scout", "class_scout.html", "class_scout" ],
    [ "ScoutButton", "class_scout_button.html", "class_scout_button" ],
    [ "Selectable", "class_selectable.html", "class_selectable" ],
    [ "Soldier", "class_soldier.html", "class_soldier" ],
    [ "SoldierButton", "class_soldier_button.html", "class_soldier_button" ],
    [ "Sound", "class_sound.html", "class_sound" ],
    [ "Terrain", "class_terrain.html", "class_terrain" ],
    [ "Unit", "class_unit.html", "class_unit" ],
    [ "UnitButton", "class_unit_button.html", "class_unit_button" ],
    [ "unknownCharacter", "classunknown_character.html", "classunknown_character" ],
    [ "WonButton", "class_won_button.html", "class_won_button" ]
];